# Generated by Django 2.2 on 2021-09-24 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Others')], default=3)),
                ('assigned_doctor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
