# Generated by Django 2.2 on 2021-09-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_nurses'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doctor_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
