# Generated by Django 2.2 on 2021-09-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0003_doctors_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='doctor_name',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
