# Generated by Django 2.2 on 2021-09-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_auto_20210924_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='person',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='case_paper',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='records',
        ),
        migrations.AddField(
            model_name='patients',
            name='history',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
