# Generated by Django 2.2 on 2021-09-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0005_auto_20210924_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
