# Generated by Django 2.2 on 2021-09-24 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0006_auto_20210924_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='assigned_doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managements.Doctors'),
        ),
    ]
